# Tensors
Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see Bridge with NumPy). Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autograd section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!

In [2]:
import torch
import numpy as np

## Initializing a Tensor

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [7]:
a = [1., 2., 3.]
type(a)

list

In [8]:
b = torch.tensor(a)
type(b)

torch.Tensor

In [9]:
b.dtype

torch.float32

In [12]:
a = np.random.normal((2, 3))
a

array([3.41492171, 2.93573123])

In [13]:
torch.tensor(a)

tensor([3.4149, 2.9357], dtype=torch.float64)

In [15]:
c = torch.ones_like(b)
c

tensor([1., 1., 1.])

In [16]:
c = torch.zeros_like(b)
c

tensor([0., 0., 0.])

In [18]:
c = torch.rand_like(b)
c

tensor([0.8030, 0.4985, 0.5070])

In [19]:
torch.rand((2, 2))

tensor([[0.5809, 0.5506],
        [0.9944, 0.8071]])

In [24]:
d = torch.rand((3, 3, 3))
d

tensor([[[0.0595, 0.8069, 0.2576],
         [0.1114, 0.1057, 0.6945],
         [0.5731, 0.1530, 0.7917]],

        [[0.4973, 0.0853, 0.8483],
         [0.5118, 0.4341, 0.5877],
         [0.3211, 0.5274, 0.5831]],

        [[0.0041, 0.5388, 0.0364],
         [0.5026, 0.3865, 0.3467],
         [0.8019, 0.4118, 0.4008]]])

In [27]:
d[1][1]

tensor([0.5118, 0.4341, 0.5877])

In [28]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[3.9532e-02, 9.4978e-01, 7.7069e-05],
        [9.7582e-01, 4.1304e-01, 4.5501e-01]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

In [33]:
a = torch.rand([2, 2])
a

tensor([[0.7185, 0.7156],
        [0.4335, 0.1885]])

In [34]:
print(a.dtype)
print(a.shape)
print(a.device)

torch.float32
torch.Size([2, 2])
cpu


In [35]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors
Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here.
https://pytorch.org/docs/stable/torch.html

In [36]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [37]:
torch.is_tensor(a)

True

In [3]:
a = torch.tensor(1.0)
a

tensor(1.)

In [4]:
torch.is_nonzero(a)

True

In [5]:
a = torch.rand([2, 2])
a

tensor([[0.9007, 0.9511],
        [0.3356, 0.5441]])

In [6]:
torch.numel(a)

4

https://pytorch.org/docs/stable/generated/torch.zeros.html#torch.zeros
torch.zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
- Parameters

size (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.

In [7]:
torch.zeros(size=(5, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
torch.zeros((5, 5), dtype=torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [9]:
a = torch.zeros((5, 5), dtype=torch.int32)
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [10]:
torch.ones_like(a)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [11]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [14]:
torch.arange(0, 5, 2)

tensor([0, 2, 4])

In [13]:
torch.range(0, 5)

C:\Users\GUMP\AppData\Local\Temp\ipykernel_16948\4222126616.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

In [15]:
torch.range(0, 5).dtype

C:\Users\GUMP\AppData\Local\Temp\ipykernel_16948\3801334473.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 5).dtype


torch.float32

torch.eye
torch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [16]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
torch.full([2, 2], 5)

tensor([[5, 5],
        [5, 5]])

## Indexing, Slicing, Joining, Mutating Ops


In [18]:
a = torch.rand([2, 2])
a

tensor([[0.0237, 0.1363],
        [0.5401, 0.6072]])

In [26]:
b = torch.rand([2, 3])
b

tensor([[0.4505, 0.8606, 0.2690],
        [0.9381, 0.6606, 0.8671]])

In [27]:
torch.cat([a, b], dim=1)

tensor([[0.0237, 0.1363, 0.4505, 0.8606, 0.2690],
        [0.5401, 0.6072, 0.9381, 0.6606, 0.8671]])

In [28]:
b = torch.rand(3, 2)
b

tensor([[0.5538, 0.1540],
        [0.6647, 0.5447],
        [0.4887, 0.3951]])

In [30]:
torch.chunk(b, 2)

(tensor([[0.5538, 0.1540],
         [0.6647, 0.5447]]),
 tensor([[0.4887, 0.3951]]))

In [32]:
torch.chunk(b, 2, dim=1)

(tensor([[0.5538],
         [0.6647],
         [0.4887]]),
 tensor([[0.1540],
         [0.5447],
         [0.3951]]))

In [33]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [39]:
torch.gather(t, 1, torch.tensor([[0, 1], [0, 0]]))

tensor([[1, 2],
        [3, 3]])

## reshape

In [2]:
a = torch.arange(4.)
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [3]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

## scatter_
Writes all values from the tensor src into self at the indices specified in the index tensor. For each value in src, its output index is specified by its index in src for dimension != dim and by the corresponding value in index for dimension = dim.

In [2]:
src = torch.arange(1, 11).reshape((2, 5))
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [4]:
index = torch.tensor([[0, 1, 2, 0]])
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)

tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [10]:
# 创建一个初始为零的2x5张量
tensor = torch.zeros(2, 5, dtype=torch.int)

# 指定要更新的索引
indices = torch.tensor([[0, 1, 2], [2, 0, 4]])

# 指定要散布的值
values = torch.tensor([[10, 20, 30], [40, 50, 60]], dtype=torch.int)

# 使用 scatter_ 更新张量
tensor.scatter_(1, indices, values)

print(tensor)

tensor([[10, 20, 30,  0,  0],
        [50,  0, 40,  0, 60]], dtype=torch.int32)


## torch.Tensor.scatter_add_
Tensor.scatter_add_(dim, index, src) → Tensor
Adds all values from the tensor src into self at the indices specified in the index tensor in a similar fashion as scatter_(). For each value in src, it is added to an index in self which is specified by its index in src for dimension != dim and by the corresponding value in index for dimension = dim.

In [12]:
src = torch.ones((2, 5))
index = torch.tensor([[0, 1, 2, 0, 0]])
torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)

tensor([[1., 0., 0., 1., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [13]:
index = torch.tensor([[0, 1, 2, 0, 0], [0, 1, 2, 2, 2]])
torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)

tensor([[2., 0., 0., 1., 1.],
        [0., 2., 0., 0., 0.],
        [0., 0., 2., 1., 1.]])

## torch.split
Splits the tensor into chunks. Each chunk is a view of the original tensor.

In [14]:
a = torch.arange(10).reshape(5, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [15]:
torch.split(a, 2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [16]:
torch.split(a, [1, 4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

chunks和split的区别，chunks是均分，split是按索引切分

## torch.squeeze
Returns a tensor with all specified dimensions of input of size 1 removed.
\begin{aligned}&\text{For example, if input is of shape:}(A\times1\times B\times C\times1\times D)\text{then the input.squeeze()will be of shape:}(A\times B\times C\times D).\\&C\times D).\end{aligned}

In [3]:
b = torch.rand((3, 2))
b

tensor([[0.0606, 0.7305],
        [0.1065, 0.4737],
        [0.7922, 0.0984]])

In [4]:
b.reshape((3, 1, 2))

tensor([[[0.0606, 0.7305]],

        [[0.1065, 0.4737]],

        [[0.7922, 0.0984]]])

In [6]:
torch.squeeze(b.reshape((3, 1, 2)))

tensor([[0.0606, 0.7305],
        [0.1065, 0.4737],
        [0.7922, 0.0984]])

In [7]:
b.reshape((3, 1, 2, 1, 1))

tensor([[[[[0.0606]],

          [[0.7305]]]],



        [[[[0.1065]],

          [[0.4737]]]],



        [[[[0.7922]],

          [[0.0984]]]]])

In [10]:
torch.squeeze(b.reshape((3, 1, 2, 1, 1)), dim=1).shape

torch.Size([3, 2, 1, 1])

In [12]:
torch.squeeze(torch.squeeze(b.reshape((3, 1, 2, 1, 1)), dim=1), dim=3).shape

torch.Size([3, 2, 1])

## torch.stack

In [17]:
a = torch.rand((3, 2))
a

tensor([[0.2525, 0.7913],
        [0.7265, 0.4550],
        [0.3567, 0.1520]])

In [20]:
torch.stack([a, b])

tensor([[[0.2525, 0.7913],
         [0.7265, 0.4550],
         [0.3567, 0.1520]],

        [[0.0606, 0.7305],
         [0.1065, 0.4737],
         [0.7922, 0.0984]]])

In [21]:
torch.stack([a, b]).shape

torch.Size([2, 3, 2])

In [23]:
torch.stack([a, b], dim=1)

tensor([[[0.2525, 0.7913],
         [0.0606, 0.7305]],

        [[0.7265, 0.4550],
         [0.1065, 0.4737]],

        [[0.3567, 0.1520],
         [0.7922, 0.0984]]])

In [24]:
torch.stack([a, b], dim=1).shape

torch.Size([3, 2, 2])

## torch.take


In [3]:
src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

## torch.tile

In [4]:
x = torch.tensor([1, 2, 3])
x.tile((2,))


tensor([1, 2, 3, 1, 2, 3])

In [5]:
y = torch.tensor([[1, 2], [3, 4]])
torch.tile(y, (2, 2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [6]:
a = torch.rand((4, 3))
a

tensor([[0.2065, 0.5958, 0.3137],
        [0.4074, 0.9023, 0.4941],
        [0.0654, 0.0123, 0.2407],
        [0.9941, 0.6870, 0.2115]])

In [7]:
a_tile = torch.tile(a, [2, 1])
a_tile

tensor([[0.2065, 0.5958, 0.3137],
        [0.4074, 0.9023, 0.4941],
        [0.0654, 0.0123, 0.2407],
        [0.9941, 0.6870, 0.2115],
        [0.2065, 0.5958, 0.3137],
        [0.4074, 0.9023, 0.4941],
        [0.0654, 0.0123, 0.2407],
        [0.9941, 0.6870, 0.2115]])

In [8]:
a_tile = torch.tile(a, [1, 2])
a_tile

tensor([[0.2065, 0.5958, 0.3137, 0.2065, 0.5958, 0.3137],
        [0.4074, 0.9023, 0.4941, 0.4074, 0.9023, 0.4941],
        [0.0654, 0.0123, 0.2407, 0.0654, 0.0123, 0.2407],
        [0.9941, 0.6870, 0.2115, 0.9941, 0.6870, 0.2115]])

## torch.transpose

In [9]:
x = torch.randn(2, 3)
x

tensor([[-1.4733,  1.3455, -1.0983],
        [-0.3163,  0.2942, -0.3462]])

In [10]:
torch.transpose(x, 0, 1)

tensor([[-1.4733, -0.3163],
        [ 1.3455,  0.2942],
        [-1.0983, -0.3462]])

In [11]:
x = torch.randn(2, 3, 4)
x

tensor([[[ 1.2729,  1.5518,  0.2730, -0.6202],
         [-0.9796, -0.5160,  0.2616,  0.5486],
         [-0.5419,  0.1019,  1.7391,  0.3459]],

        [[ 0.4020, -0.2897, -1.0111,  0.4349],
         [-2.4499,  0.3791,  1.3360,  1.7051],
         [-1.2362, -1.2125, -1.7621, -0.4036]]])

In [12]:
torch.transpose(x, 0, 1)

tensor([[[ 1.2729,  1.5518,  0.2730, -0.6202],
         [ 0.4020, -0.2897, -1.0111,  0.4349]],

        [[-0.9796, -0.5160,  0.2616,  0.5486],
         [-2.4499,  0.3791,  1.3360,  1.7051]],

        [[-0.5419,  0.1019,  1.7391,  0.3459],
         [-1.2362, -1.2125, -1.7621, -0.4036]]])

In [13]:
torch.transpose(x, 0, 2)

tensor([[[ 1.2729,  0.4020],
         [-0.9796, -2.4499],
         [-0.5419, -1.2362]],

        [[ 1.5518, -0.2897],
         [-0.5160,  0.3791],
         [ 0.1019, -1.2125]],

        [[ 0.2730, -1.0111],
         [ 0.2616,  1.3360],
         [ 1.7391, -1.7621]],

        [[-0.6202,  0.4349],
         [ 0.5486,  1.7051],
         [ 0.3459, -0.4036]]])

In [14]:
torch.transpose(x, 1, 2)

tensor([[[ 1.2729, -0.9796, -0.5419],
         [ 1.5518, -0.5160,  0.1019],
         [ 0.2730,  0.2616,  1.7391],
         [-0.6202,  0.5486,  0.3459]],

        [[ 0.4020, -2.4499, -1.2362],
         [-0.2897,  0.3791, -1.2125],
         [-1.0111,  1.3360, -1.7621],
         [ 0.4349,  1.7051, -0.4036]]])

## torch.unbind
Removes a tensor dimension.

Returns a tuple of all slices along a given dimension, already without it.

In [20]:
torch.unbind(torch.tensor([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]]), dim=0)

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [21]:
torch.unbind(torch.tensor([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]]), dim=1)

(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))

## torch.unsqueeze
Returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.

In [22]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [23]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [25]:
torch.unsqueeze(torch.unsqueeze(x, 1), 2)

tensor([[[1]],

        [[2]],

        [[3]],

        [[4]]])

In [26]:
a = torch.rand((2, 3, 4))
a

tensor([[[0.1273, 0.1692, 0.8631, 0.0336],
         [0.8131, 0.6181, 0.4488, 0.1545],
         [0.2858, 0.2192, 0.2868, 0.8485]],

        [[0.5839, 0.4427, 0.0530, 0.2388],
         [0.3488, 0.0416, 0.4055, 0.5547],
         [0.7031, 0.2600, 0.0066, 0.0870]]])

In [28]:
torch.unsqueeze(a, dim=0).shape

torch.Size([1, 2, 3, 4])

In [30]:
torch.unsqueeze(a, dim=1).shape

torch.Size([2, 1, 3, 4])

In [31]:
torch.unsqueeze(a, dim=2).shape

torch.Size([2, 3, 1, 4])

In [32]:
torch.unsqueeze(a, dim=3).shape

torch.Size([2, 3, 4, 1])

## torch.where
Return a tensor of elements selected from either input or other, depending on condition.

In [34]:
x = torch.randn(3, 2)
x

tensor([[-1.1804,  0.4913],
        [-0.1050,  0.4583],
        [-1.7445,  0.2130]])

In [35]:
y = torch.ones(3, 2)
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [36]:
torch.where(x > 0, x, y)

tensor([[1.0000, 0.4913],
        [1.0000, 0.4583],
        [1.0000, 0.2130]])

In [37]:
x = torch.randn(2, 2, dtype=torch.double)
x

tensor([[-0.5172, -0.0088],
        [ 0.2159, -1.5364]], dtype=torch.float64)

In [38]:
torch.where(x > 0, x, 0.)

tensor([[0.0000, 0.0000],
        [0.2159, 0.0000]], dtype=torch.float64)

## torch.bernoulli

In [39]:
# Example tensor of probabilities
probabilities = torch.tensor([0.2, 0.5, 0.8])

# Generate Bernoulli-distributed tensor
samples = torch.bernoulli(probabilities)

print(samples)


tensor([0., 0., 0.])


## torch.normal

In [3]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([ 1.3757,  3.0206,  3.5284,  3.5768,  5.2523,  5.3164,  7.2764,  8.0957,
         8.9983, 10.0616])

In [4]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))

tensor([ 0.8713,  0.5995,  2.8443, -8.3190, -3.5281])

In [5]:
torch.normal(mean=torch.arange(1., 6.))

tensor([1.4812, 1.3544, 0.9861, 4.1076, 5.3617])

In [6]:
torch.normal(2, 3, size=(1, 4))

tensor([[3.7882, 1.9030, 5.8235, 2.0335]])