# nn.module

register_parameters使用

In [ ]:
import torch
import torch.nn as nn


class GaussianModule1(nn.Module):
    def __init__(self):
        super(GaussianModule1, self).__init__()
        self.mean = nn.Parameter(torch.zeros(1))
        self.pdf = torch.distributions.Normal(self.mean, torch.tensor([1.0]))

    def forward(self, x):
        return -self.pdf.log_prob(x)

In [ ]:
import torch
import torch.nn as nn


class GaussianModule2(nn.Module):
    def __init__(self):
        super(GaussianModule2, self).__init__()
        self.register_parameter('mean', nn.Parameter(torch.zeros(1), requires_grad=True))
        self.pdf = torch.distributions.Normal(self.state_dict()['mean'], torch.tensor([1.0]))

    def forward(self, x):
        return -self.pdf.log_prob(x)


model = GaussianModule2()

### to 函数

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Test(nn.Module):
    def __init__(self):
        super(Test, self).__init__()
        self.linear1 = torch.nn.Linear(2, 3)
        self.linear2 = torch.nn.Linear(3, 4)
        self.batch_norm = torch.nn.BatchNorm2d(4)

In [3]:
test_module = Test()

In [7]:
test_module._modules

OrderedDict([('linear1', Linear(in_features=2, out_features=3, bias=True)),
             ('linear2', Linear(in_features=3, out_features=4, bias=True)),
             ('batch_norm',
              BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))])

In [8]:
test_module._modules['linear1']

Linear(in_features=2, out_features=3, bias=True)

In [9]:
test_module._modules['linear1'].weight

Parameter containing:
tensor([[ 0.5888,  0.0987],
        [ 0.3845, -0.1014],
        [-0.4606, -0.3230]], requires_grad=True)

In [10]:
test_module._modules['linear1'].weight.dtype

torch.float32

In [11]:
test_module.to(torch.double)

Test(
  (linear1): Linear(in_features=2, out_features=3, bias=True)
  (linear2): Linear(in_features=3, out_features=4, bias=True)
  (batch_norm): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

In [12]:
test_module._modules['linear1'].weight.dtype

torch.float64

In [13]:
test_module._modules

OrderedDict([('linear1', Linear(in_features=2, out_features=3, bias=True)),
             ('linear2', Linear(in_features=3, out_features=4, bias=True)),
             ('batch_norm',
              BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))])

In [14]:
test_module._parameters

OrderedDict()

In [15]:
test_module._buffers

OrderedDict()

In [17]:
test_module.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.5888,  0.0987],
                      [ 0.3845, -0.1014],
                      [-0.4606, -0.3230]], dtype=torch.float64)),
             ('linear1.bias',
              tensor([ 0.1983,  0.5601, -0.6631], dtype=torch.float64)),
             ('linear2.weight',
              tensor([[-0.5773, -0.1535, -0.1847],
                      [-0.1336, -0.4034, -0.1039],
                      [-0.2214, -0.2823,  0.2440],
                      [-0.5242,  0.4611,  0.1813]], dtype=torch.float64)),
             ('linear2.bias',
              tensor([ 0.0048, -0.1528, -0.1939,  0.2461], dtype=torch.float64)),
             ('batch_norm.weight',
              tensor([1., 1., 1., 1.], dtype=torch.float64)),
             ('batch_norm.bias',
              tensor([0., 0., 0., 0.], dtype=torch.float64)),
             ('batch_norm.running_mean',
              tensor([0., 0., 0., 0.], dtype=torch.float64)),
             ('batch_norm.running_var',
        

In [18]:
for p in test_module.parameters():
    print(p)

Parameter containing:
tensor([[ 0.5888,  0.0987],
        [ 0.3845, -0.1014],
        [-0.4606, -0.3230]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([ 0.1983,  0.5601, -0.6631], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.5773, -0.1535, -0.1847],
        [-0.1336, -0.4034, -0.1039],
        [-0.2214, -0.2823,  0.2440],
        [-0.5242,  0.4611,  0.1813]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([ 0.0048, -0.1528, -0.1939,  0.2461], dtype=torch.float64,
       requires_grad=True)
Parameter containing:
tensor([1., 1., 1., 1.], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0.], dtype=torch.float64, requires_grad=True)


In [19]:
for p in test_module.named_parameters():
    print(p)

('linear1.weight', Parameter containing:
tensor([[ 0.5888,  0.0987],
        [ 0.3845, -0.1014],
        [-0.4606, -0.3230]], dtype=torch.float64, requires_grad=True))
('linear1.bias', Parameter containing:
tensor([ 0.1983,  0.5601, -0.6631], dtype=torch.float64, requires_grad=True))
('linear2.weight', Parameter containing:
tensor([[-0.5773, -0.1535, -0.1847],
        [-0.1336, -0.4034, -0.1039],
        [-0.2214, -0.2823,  0.2440],
        [-0.5242,  0.4611,  0.1813]], dtype=torch.float64, requires_grad=True))
('linear2.bias', Parameter containing:
tensor([ 0.0048, -0.1528, -0.1939,  0.2461], dtype=torch.float64,
       requires_grad=True))
('batch_norm.weight', Parameter containing:
tensor([1., 1., 1., 1.], dtype=torch.float64, requires_grad=True))
('batch_norm.bias', Parameter containing:
tensor([0., 0., 0., 0.], dtype=torch.float64, requires_grad=True))


In [20]:
for p in test_module.named_children():
    print(p)

('linear1', Linear(in_features=2, out_features=3, bias=True))
('linear2', Linear(in_features=3, out_features=4, bias=True))
('batch_norm', BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))


In [4]:
str(test_module)

'Test(\n  (linear1): Linear(in_features=2, out_features=3, bias=True)\n  (linear2): Linear(in_features=3, out_features=4, bias=True)\n  (batch_norm): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n)'

In [5]:
dir(test_module)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_compiled_call_impl',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_se

## nn.Sequential

In [8]:
s = torch.nn.Sequential(
    torch.nn.Linear(2, 3),
    torch.nn.Linear(3, 4)
)

In [9]:
s

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=4, bias=True)
)

In [10]:
s._modules

OrderedDict([('0', Linear(in_features=2, out_features=3, bias=True)),
             ('1', Linear(in_features=3, out_features=4, bias=True))])