# 自定义层
构造一个没有任何参数的自定义层

In [3]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()


layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的模型中

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.2107e-08, grad_fn=<MeanBackward0>)

带参数的图层

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units, ))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)


dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-0.4836,  0.4025,  1.5498],
        [ 0.0982,  0.5752, -0.0841],
        [ 0.4741,  0.3199, -1.5907],
        [-0.5675, -0.5607, -1.6234],
        [ 0.8164,  0.2211, -1.0114]], requires_grad=True)

使用自定义层直接执行正向传播计算

In [6]:
dense(torch.rand(2, 5))

tensor([[1.7943, 0.4650, 0.0000],
        [1.1567, 0.1261, 0.0000]])

使用自定义层构建模型

In [7]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[16.2551],
        [14.9196]])